from __future__ import annotations

import json
import textwrap
from collections.abc import Callable

from .models import GenerateRequest, GeneratedFile


def clean(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def file(path: str, content: str) -> GeneratedFile:
    return GeneratedFile(path=path, content=clean(content))


def slug(request: GenerateRequest) -> str:
    return request.project_name.lower().replace("_", "-")


def python_requirements(request: GenerateRequest, framework: str) -> list[str]:
    requirements = [framework]
    if request.database == "postgresql":
        requirements.append("psycopg[binary]>=3.2,<4")
    elif request.database == "sqlite":
        requirements.append("sqlalchemy>=2.0,<3")
    if request.auth == "jwt":
        requirements.append("PyJWT>=2.10,<3")
    requirements.append("pytest>=8.4,<9")
    return requirements


def shared_files(request: GenerateRequest, framework_name: str) -> list[GeneratedFile]:
    features = "\n".join(f"- {feature}" for feature in request.features) or "- Health check"
    files = [
        file(
            ".env.example",
            f"""
            APP_NAME={request.project_name}
            APP_ENV=development
            DATABASE_URL=
            AUTH_SECRET=change-me
            """,
        ),
        file(
            ".gitignore",
            """
            .env
            .DS_Store
            node_modules/
            .next/
            dist/
            build/
            coverage/
            __pycache__/
            .pytest_cache/
            .venv/
            vendor/
            target/
            bin/
            obj/
            """,
        ),
        file(
            "README.md",
            f"""
            # {request.project_name}

            {request.description}

            Generated by DevForge as a {framework_name} starter.

            ## Selected architecture

            - Database: `{request.database}`
            - Authentication: `{request.auth}`
            - Tests: `{request.test_level}`
            - Package manager: `{request.package_manager}`

            ## Requested features

            {features}

            ## Start

            Copy `.env.example` to `.env`, install dependencies using the
            framework's package manager, and run the development command from
            the dependency manifest.

            ## Health check

            The starter exposes `/health` (or an equivalent health endpoint)
            and includes a smoke test.
            """,
        ),
    ]
    if request.docker:
        files.extend(docker_files(request))
    if request.ci:
        files.append(ci_file(request))
    return files


def docker_files(request: GenerateRequest) -> list[GeneratedFile]:
    commands = {
        "flask": ("python:3.12-slim", "pip install -r requirements.txt", "python -m app", 8000),
        "fastapi": (
            "python:3.12-slim",
            "pip install -r requirements.txt",
            "uvicorn app.main:app --host 0.0.0.0 --port 8000",
            8000,
        ),
        "django": (
            "python:3.12-slim",
            "pip install -r requirements.txt",
            "python manage.py runserver 0.0.0.0:8000",
            8000,
        ),
        "spring": ("maven:3.9-eclipse-temurin-21", "mvn package -DskipTests", "java -jar target/app.jar", 8080),
        "rails": ("ruby:3.3", "bundle install", "bundle exec rails server -b 0.0.0.0", 3000),
        "laravel": ("composer:2", "composer install --no-interaction", "php artisan serve --host=0.0.0.0", 8000),
        "aspnet": ("mcr.microsoft.com/dotnet/sdk:8.0", "dotnet restore", "dotnet run --urls http://0.0.0.0:8080", 8080),
    }
    if request.framework_id in commands:
        image, install, command, port = commands[request.framework_id]
        return [
            file(
                "Dockerfile",
                f"""
                FROM {image}
                WORKDIR /app
                COPY . .
                RUN {install}
                EXPOSE {port}
                CMD ["sh", "-c", "{command}"]
                """,
            )
        ]
    start = (
        "npm run start -- --host 0.0.0.0 --port 3000"
        if request.framework_id in {"react", "vue", "svelte"}
        else "npm run start -- --host 0.0.0.0"
        if request.framework_id == "angular"
        else "npm run start"
    )
    return [
        file(
            "Dockerfile",
            f"""
            FROM node:22-alpine
            WORKDIR /app
            COPY package*.json ./
            RUN npm install
            COPY . .
            RUN npm run build --if-present
            EXPOSE 3000
            CMD ["sh", "-c", "{start}"]
            """,
        )
    ]


def ci_file(request: GenerateRequest) -> GeneratedFile:
    if request.framework_id in {"flask", "fastapi", "django"}:
        steps = [
            "      - uses: actions/setup-python@v5",
            "        with:",
            '          python-version: "3.12"',
            "      - run: pip install -r requirements.txt",
            "      - run: pytest",
        ]
    elif request.framework_id == "spring":
        steps = [
            "      - uses: actions/setup-java@v4",
            "        with:",
            "          distribution: temurin",
            '          java-version: "21"',
            "      - run: mvn test",
        ]
    elif request.framework_id == "rails":
        steps = [
            "      - uses: ruby/setup-ruby@v1",
            "        with:",
            '          ruby-version: "3.3"',
            "          bundler-cache: true",
            "      - run: bundle exec rails test",
        ]
    elif request.framework_id == "laravel":
        steps = [
            "      - uses: shivammathur/setup-php@v2",
            "        with:",
            '          php-version: "8.3"',
            "      - run: composer install --no-interaction",
            "      - run: vendor/bin/phpunit",
        ]
    elif request.framework_id == "aspnet":
        steps = [
            "      - uses: actions/setup-dotnet@v4",
            "        with:",
            '          dotnet-version: "8.0.x"',
            "      - run: dotnet test tests/*.csproj",
        ]
    else:
        manager = request.package_manager
        prefix = f"{manager} " if manager != "npm" else "npm "
        steps = [
            "      - uses: actions/setup-node@v4",
            "        with:",
            '          node-version: "22"',
            f"      - run: {'corepack enable && ' if manager != 'npm' else ''}{prefix}install",
            f"      - run: {prefix}test -- --run",
            f"      - run: {prefix}run build --if-present",
        ]

    workflow = "\n".join(
        [
            "name: CI",
            "",
            "on:",
            "  push:",
            "  pull_request:",
            "",
            "jobs:",
            "  test:",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            *steps,
        ]
    )
    return file(".github/workflows/ci.yml", workflow)


def flask(request: GenerateRequest) -> list[GeneratedFile]:
    requirements = python_requirements(request, "Flask>=3.1,<4")
    return [
        file("requirements.txt", "\n".join(requirements)),
        file("pytest.ini", "[pytest]\npythonpath = .\ntestpaths = tests"),
        file(
            "app.py",
            f'''
            from flask import Flask, jsonify

            app = Flask(__name__)

            @app.get("/")
            def index():
                return jsonify(name="{request.project_name}", status="ready")

            @app.get("/health")
            def health():
                return jsonify(status="ok")

            if __name__ == "__main__":
                app.run(host="0.0.0.0", port=8000, debug=True)
            ''',
        ),
        file(
            "tests/test_app.py",
            """
            from app import app

            def test_health():
                response = app.test_client().get("/health")
                assert response.status_code == 200
                assert response.get_json() == {"status": "ok"}
            """,
        ),
        *shared_files(request, "Flask"),
    ]


def fastapi(request: GenerateRequest) -> list[GeneratedFile]:
    requirements = python_requirements(request, "fastapi>=0.139,<1")
    requirements.extend(["uvicorn[standard]>=0.35,<1", "httpx>=0.28,<1"])
    return [
        file("requirements.txt", "\n".join(requirements)),
        file("pytest.ini", "[pytest]\npythonpath = .\ntestpaths = tests"),
        file("app/__init__.py", ""),
        file(
            "app/main.py",
            f'''
            from fastapi import FastAPI

            app = FastAPI(title="{request.project_name}")

            @app.get("/")
            def index():
                return {{"name": "{request.project_name}", "status": "ready"}}

            @app.get("/health")
            def health():
                return {{"status": "ok"}}
            ''',
        ),
        file(
            "tests/test_main.py",
            """
            from fastapi.testclient import TestClient
            from app.main import app

            def test_health():
                assert TestClient(app).get("/health").json() == {"status": "ok"}
            """,
        ),
        *shared_files(request, "FastAPI"),
    ]


def django(request: GenerateRequest) -> list[GeneratedFile]:
    requirements = python_requirements(request, "Django>=5.2,<6")
    database = (
        "'ENGINE': 'django.db.backends.postgresql', 'NAME': os.getenv('DATABASE_URL', '')"
        if request.database == "postgresql"
        else "'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'"
    )
    return [
        file("requirements.txt", "\n".join(requirements)),
        file("pytest.ini", "[pytest]\npythonpath = .\ntestpaths = tests"),
        file(
            "manage.py",
            """
            #!/usr/bin/env python
            import os, sys
            os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
            from django.core.management import execute_from_command_line
            execute_from_command_line(sys.argv)
            """,
        ),
        file("config/__init__.py", ""),
        file(
            "config/settings.py",
            f"""
            import os
            from pathlib import Path
            BASE_DIR = Path(__file__).resolve().parent.parent
            SECRET_KEY = os.getenv("AUTH_SECRET", "dev-only")
            DEBUG = True
            ROOT_URLCONF = "config.urls"
            ALLOWED_HOSTS = ["*"]
            MIDDLEWARE = []
            INSTALLED_APPS = []
            DATABASES = {{"default": {{{database}}}}}
            DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
            """,
        ),
        file(
            "config/urls.py",
            f'''
            from django.http import JsonResponse
            from django.urls import path

            def index(_request):
                return JsonResponse({{"name": "{request.project_name}", "status": "ready"}})

            def health(_request):
                return JsonResponse({{"status": "ok"}})

            urlpatterns = [path("", index), path("health", health)]
            ''',
        ),
        file(
            "tests/test_health.py",
            """
            import os
            os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
            import django
            django.setup()
            from django.test import Client

            def test_health():
                assert Client().get("/health").json() == {"status": "ok"}
            """,
        ),
        *shared_files(request, "Django"),
    ]


def js_package(
    request: GenerateRequest,
    scripts: dict[str, str],
    dependencies: dict[str, str],
    dev_dependencies: dict[str, str],
    module: bool = True,
) -> GeneratedFile:
    package = {
        "name": slug(request),
        "version": "0.1.0",
        "private": True,
        **({"type": "module"} if module else {}),
        "scripts": scripts,
        "dependencies": dependencies,
        "devDependencies": dev_dependencies,
        "engines": {"node": ">=22"},
    }
    return file("package.json", json.dumps(package, indent=2))


def node_api(request: GenerateRequest, express: bool) -> list[GeneratedFile]:
    dependencies: dict[str, str] = {}
    entry = "src/server.js"
    if express:
        dependencies["express"] = "^5.1.0"
        source = f'''
        import express from "express";
        const app = express();
        app.use(express.json());
        app.get("/", (_req, res) => res.json({{ name: "{request.project_name}", status: "ready" }}));
        app.get("/health", (_req, res) => res.json({{ status: "ok" }}));
        if (process.env.NODE_ENV !== "test") app.listen(process.env.PORT || 3000);
        export default app;
        '''
        test = """
        import { describe, expect, it } from "vitest";
        import request from "supertest";
        import app from "../src/server.js";
        describe("health", () => it("responds", async () => {
          const response = await request(app).get("/health");
          expect(response.body).toEqual({ status: "ok" });
        }));
        """
        dev_dependencies = {"supertest": "^7.1.0", "vitest": "^3.2.0"}
    else:
        source = f'''
        import {{ createServer }} from "node:http";
        export const server = createServer((req, res) => {{
          res.setHeader("content-type", "application/json");
          if (req.url === "/health") return res.end(JSON.stringify({{ status: "ok" }}));
          res.end(JSON.stringify({{ name: "{request.project_name}", status: "ready" }}));
        }});
        if (process.env.NODE_ENV !== "test") server.listen(process.env.PORT || 3000);
        '''
        test = """
        import { afterAll, describe, expect, it } from "vitest";
        import { server } from "../src/server.js";
        afterAll(() => server.close());
        describe("server", () => it("is defined", () => expect(server).toBeDefined()));
        """
        dev_dependencies = {"vitest": "^3.2.0"}
    if request.auth == "jwt":
        dependencies["jsonwebtoken"] = "^9.0.2"
    if request.database == "postgresql":
        dependencies["pg"] = "^8.16.0"
    elif request.database == "mongodb":
        dependencies["mongodb"] = "^6.17.0"
    elif request.database == "sqlite":
        dependencies["better-sqlite3"] = "^12.0.0"
    return [
        js_package(
            request,
            {"dev": f"node --watch {entry}", "start": f"node {entry}", "test": "vitest run"},
            dependencies,
            dev_dependencies,
        ),
        file(entry, source),
        file("tests/health.test.js", test),
        *shared_files(request, "Express.js" if express else "Node.js"),
    ]


def react(request: GenerateRequest) -> list[GeneratedFile]:
    return [
        js_package(
            request,
            {"dev": "vite", "build": "vite build", "start": "vite preview", "test": "vitest run"},
            {"@vitejs/plugin-react": "^4.6.0", "vite": "^7.0.0", "react": "^19.1.0", "react-dom": "^19.1.0"},
            {"vitest": "^3.2.0"},
        ),
        file(
            "vite.config.js",
            'import { defineConfig } from "vite"; import react from "@vitejs/plugin-react"; export default defineConfig({ plugins: [react()] });',
        ),
        file("index.html", '<div id="root"></div><script type="module" src="/src/main.jsx"></script>'),
        file(
            "src/main.jsx",
            """
            import React from "react";
            import { createRoot } from "react-dom/client";
            import "./style.css";
            import App from "./App.jsx";
            createRoot(document.getElementById("root")).render(<App />);
            """,
        ),
        file(
            "src/App.jsx",
            f'''
            export default function App() {{
              return <main><span>Ready to build</span><h1>{request.project_name}</h1><p>{request.description}</p></main>;
            }}
            ''',
        ),
        file("src/style.css", "body { margin: 0; font-family: system-ui; } main { max-width: 720px; margin: 15vh auto; padding: 2rem; }"),
        file("src/App.test.jsx", 'import { expect, test } from "vitest"; test("health", () => expect(true).toBe(true));'),
        *shared_files(request, "React and Vite"),
    ]


def vue(request: GenerateRequest) -> list[GeneratedFile]:
    return [
        js_package(
            request,
            {"dev": "vite", "build": "vite build", "start": "vite preview", "test": "vitest run"},
            {"@vitejs/plugin-vue": "^6.0.0", "vite": "^7.0.0", "vue": "^3.5.0"},
            {"vitest": "^3.2.0"},
        ),
        file(
            "vite.config.js",
            'import { defineConfig } from "vite"; import vue from "@vitejs/plugin-vue"; export default defineConfig({ plugins: [vue()] });',
        ),
        file("index.html", '<div id="app"></div><script type="module" src="/src/main.js"></script>'),
        file("src/main.js", 'import { createApp } from "vue"; import App from "./App.vue"; createApp(App).mount("#app");'),
        file(
            "src/App.vue",
            f"""
            <template><main><span>Ready to build</span><h1>{request.project_name}</h1><p>{request.description}</p></main></template>
            <style>body {{ margin: 0; font-family: system-ui }} main {{ max-width: 720px; margin: 15vh auto; padding: 2rem }}</style>
            """,
        ),
        file("tests/app.test.js", 'import { expect, test } from "vitest"; test("health", () => expect(true).toBe(true));'),
        *shared_files(request, "Vue.js"),
    ]


def svelte(request: GenerateRequest) -> list[GeneratedFile]:
    return [
        js_package(
            request,
            {"dev": "vite", "build": "vite build", "start": "vite preview", "test": "vitest run"},
            {"@sveltejs/vite-plugin-svelte": "^6.0.0", "vite": "^7.0.0", "svelte": "^5.0.0"},
            {"vitest": "^3.2.0"},
        ),
        file(
            "vite.config.js",
            'import { defineConfig } from "vite"; import { svelte } from "@sveltejs/vite-plugin-svelte"; export default defineConfig({ plugins: [svelte()] });',
        ),
        file("index.html", '<div id="app"></div><script type="module" src="/src/main.js"></script>'),
        file("src/main.js", 'import { mount } from "svelte"; import App from "./App.svelte"; mount(App, { target: document.getElementById("app") });'),
        file("src/App.svelte", f"<main><span>Ready to build</span><h1>{request.project_name}</h1><p>{request.description}</p></main>"),
        file("tests/app.test.js", 'import { expect, test } from "vitest"; test("health", () => expect(true).toBe(true));'),
        *shared_files(request, "Svelte"),
    ]


def angular(request: GenerateRequest) -> list[GeneratedFile]:
    package = js_package(
        request,
        {"dev": "ng serve", "build": "ng build", "start": "ng serve", "test": "vitest run"},
        {"@angular/animations": "20.3.26", "@angular/common": "20.3.26", "@angular/compiler": "20.3.26", "@angular/core": "20.3.26", "@angular/platform-browser": "20.3.26", "rxjs": "^7.8.0", "tslib": "^2.8.0", "zone.js": "^0.15.0"},
        {"@angular-devkit/build-angular": "20.3.32", "@angular/cli": "20.3.32", "@angular/compiler-cli": "20.3.26", "typescript": "5.9.2", "vitest": "^3.2.7"},
    )
    return [
        package,
        file(
            "angular.json",
            json.dumps({"version": 1, "projects": {slug(request): {"projectType": "application", "root": "", "sourceRoot": "src", "architect": {"build": {"builder": "@angular-devkit/build-angular:application", "options": {"browser": "src/main.ts", "index": "src/index.html", "tsConfig": "tsconfig.app.json"}}}}}}, indent=2),
        ),
        file("tsconfig.json", '{"compilerOptions":{"target":"ES2022","module":"ES2022","moduleResolution":"bundler","experimentalDecorators":true,"skipLibCheck":true,"types":[]},"angularCompilerOptions":{"strictTemplates":true}}'),
        file("tsconfig.app.json", '{"extends":"./tsconfig.json","compilerOptions":{"outDir":"./out-tsc/app"},"files":["src/main.ts"]}'),
        file("src/index.html", '<app-root></app-root>'),
        file(
            "src/main.ts",
            f'''
            import {{ Component }} from "@angular/core";
            import {{ bootstrapApplication }} from "@angular/platform-browser";
            @Component({{selector:"app-root", standalone:true, template:`<main><h1>{request.project_name}</h1><p>{request.description}</p></main>`}})
            class AppComponent {{}}
            bootstrapApplication(AppComponent);
            ''',
        ),
        file("src/main.test.ts", 'import { expect, test } from "vitest"; test("app", () => expect(true).toBe(true));'),
        *shared_files(request, "Angular"),
    ]


def nextjs(request: GenerateRequest) -> list[GeneratedFile]:
    deps = {"next": "^16.2.0", "react": "^19.2.0", "react-dom": "^19.2.0"}
    if request.database == "postgresql":
        deps["pg"] = "^8.16.0"
    elif request.database == "sqlite":
        deps["better-sqlite3"] = "^12.0.0"
    return [
        js_package(
            request,
            {"dev": "next dev", "build": "next build", "start": "next start", "test": "vitest run"},
            deps,
            {"@types/node": "^24.0.0", "@types/react": "^19.1.0", "typescript": "^5.8.0", "vitest": "^3.2.0"},
        ),
        file("tsconfig.json", '{"compilerOptions":{"target":"ES2022","lib":["dom","esnext"],"strict":true,"jsx":"preserve","module":"esnext","moduleResolution":"bundler","noEmit":true},"include":["next-env.d.ts","**/*.ts","**/*.tsx"]}'),
        file("next-env.d.ts", '/// <reference types="next" />'),
        file("app/layout.tsx", 'export default function Layout({children}:{children:React.ReactNode}) { return <html lang="en"><body>{children}</body></html> }'),
        file("app/page.tsx", f'export default function Page() {{ return <main><h1>{request.project_name}</h1><p>{request.description}</p></main> }}'),
        file("app/api/health/route.ts", 'export function GET() { return Response.json({status:"ok"}) }'),
        file("tests/health.test.ts", 'import { expect, test } from "vitest"; test("health", () => expect(true).toBe(true));'),
        *shared_files(request, "Next.js"),
    ]


def spring(request: GenerateRequest) -> list[GeneratedFile]:
    group = "com.devforge.app"
    db_dep = {
        "h2": '<dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>runtime</scope></dependency>',
        "postgresql": '<dependency><groupId>org.postgresql</groupId><artifactId>postgresql</artifactId><scope>runtime</scope></dependency>',
        "mysql": '<dependency><groupId>com.mysql</groupId><artifactId>mysql-connector-j</artifactId><scope>runtime</scope></dependency>',
    }[request.database]
    return [
        file(
            "pom.xml",
            f"""
            <project xmlns="http://maven.apache.org/POM/4.0.0">
              <modelVersion>4.0.0</modelVersion>
              <parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.5.0</version></parent>
              <groupId>{group}</groupId><artifactId>{slug(request)}</artifactId><version>0.1.0</version>
              <properties><java.version>21</java.version></properties>
              <dependencies>
                <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
                <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
                {db_dep}
              </dependencies>
              <build><finalName>app</finalName><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build>
            </project>
            """,
        ),
        file(
            "src/main/java/com/devforge/app/Application.java",
            f'''
            package {group};
            import java.util.Map;
            import org.springframework.boot.SpringApplication;
            import org.springframework.boot.autoconfigure.SpringBootApplication;
            import org.springframework.web.bind.annotation.GetMapping;
            import org.springframework.web.bind.annotation.RestController;
            @SpringBootApplication @RestController
            public class Application {{
              public static void main(String[] args) {{ SpringApplication.run(Application.class, args); }}
              @GetMapping("/") Map<String,String> index() {{ return Map.of("name","{request.project_name}","status","ready"); }}
              @GetMapping("/health") Map<String,String> health() {{ return Map.of("status","ok"); }}
            }}
            ''',
        ),
        file("src/test/java/com/devforge/app/ApplicationTests.java", f'package {group}; import org.junit.jupiter.api.Test; class ApplicationTests {{ @Test void starts() {{}} }}'),
        file("src/main/resources/application.properties", "spring.application.name=" + slug(request)),
        *shared_files(request, "Spring Boot"),
    ]


def laravel(request: GenerateRequest) -> list[GeneratedFile]:
    return [
        file(
            "composer.json",
            json.dumps(
                {
                    "name": f"devforge/{slug(request)}",
                    "type": "project",
                    "require": {"php": "^8.3", "laravel/framework": "^12.0"},
                    "require-dev": {"phpunit/phpunit": "^11.0"},
                    "autoload": {"psr-4": {"App\\": "app/"}},
                    "scripts": {"test": "phpunit"},
                },
                indent=2,
            ),
        ),
        file(
            "artisan",
            """
            #!/usr/bin/env php
            <?php
            define('LARAVEL_START', microtime(true));
            require __DIR__.'/vendor/autoload.php';
            $app = require_once __DIR__.'/bootstrap/app.php';
            $status = $app->handleCommand(new Symfony\\Component\\Console\\Input\\ArgvInput);
            exit($status);
            """,
        ),
        file(
            "bootstrap/app.php",
            """
            <?php
            use Illuminate\\Foundation\\Application;
            use Illuminate\\Foundation\\Configuration\\Exceptions;
            use Illuminate\\Foundation\\Configuration\\Middleware;
            return Application::configure(basePath: dirname(__DIR__))
              ->withRouting(web: __DIR__.'/../routes/web.php', health: '/up')
              ->withMiddleware(fn (Middleware $middleware) => null)
              ->withExceptions(fn (Exceptions $exceptions) => null)->create();
            """,
        ),
        file(
            "routes/web.php",
            f"""
            <?php
            use Illuminate\\Support\\Facades\\Route;
            Route::get('/', fn () => response()->json(['name' => '{request.project_name}', 'status' => 'ready']));
            Route::get('/health', fn () => response()->json(['status' => 'ok']));
            """,
        ),
        file("public/index.php", "<?php require __DIR__.'/../vendor/autoload.php'; $app = require_once __DIR__.'/../bootstrap/app.php'; $app->handleRequest(Illuminate\\Http\\Request::capture());"),
        file("phpunit.xml", '<phpunit bootstrap="vendor/autoload.php"><testsuites><testsuite name="Feature"><directory>tests</directory></testsuite></testsuites></phpunit>'),
        file("tests/HealthTest.php", '<?php use PHPUnit\\Framework\\TestCase; final class HealthTest extends TestCase { public function testStarter(): void { $this->assertTrue(true); } }'),
        file("bootstrap/cache/.gitkeep", ""),
        file("storage/framework/cache/.gitkeep", ""),
        file("storage/framework/sessions/.gitkeep", ""),
        file("storage/framework/views/.gitkeep", ""),
        file("storage/logs/.gitkeep", ""),
        *shared_files(request, "Laravel"),
    ]


def rails(request: GenerateRequest) -> list[GeneratedFile]:
    adapter = {"sqlite": "sqlite3", "postgresql": "pg", "mysql": "mysql2"}[request.database]
    database_config = (
        f"default: &default\n  adapter: sqlite3\n  pool: 5\n  timeout: 5000\n"
        f"development:\n  <<: *default\n  database: storage/{slug(request)}_development.sqlite3\n"
        f"test:\n  <<: *default\n  database: storage/{slug(request)}_test.sqlite3"
        if request.database == "sqlite"
        else f"default: &default\n  adapter: {adapter}\n  pool: 5\n  url: <%= ENV['DATABASE_URL'] %>\n"
        f"development:\n  <<: *default\n  database: {slug(request)}_development\n"
        f"test:\n  <<: *default\n  database: {slug(request)}_test"
    )
    return [
        file(
            "Gemfile",
            f'''
            source "https://rubygems.org"
            gem "rails", "~> 8.0"
            gem "{adapter}"
            gem "puma"
            ''',
        ),
        file("Rakefile", 'require_relative "config/application"\nRails.application.load_tasks'),
        file(
            "config/application.rb",
            f'''
            require_relative "boot"
            require "rails/all"
            Bundler.require(*Rails.groups)
            module {request.project_name.replace("-", "").replace("_", "")}
              class Application < Rails::Application
                config.load_defaults 8.0
                config.api_only = true
              end
            end
            ''',
        ),
        file("config/boot.rb", 'ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)\nrequire "bundler/setup"'),
        file("config/environment.rb", 'require_relative "application"\nRails.application.initialize!'),
        file("config/routes.rb", 'Rails.application.routes.draw do\n  get "/health", to: "health#show"\n  root to: "health#index"\nend'),
        file("config.ru", 'require_relative "config/environment"\nrun Rails.application'),
        file("bin/rails", '#!/usr/bin/env ruby\nAPP_PATH = File.expand_path("../config/application", __dir__)\nrequire_relative "../config/boot"\nrequire "rails/commands"'),
        file("app/controllers/application_controller.rb", "class ApplicationController < ActionController::API\nend"),
        file("app/controllers/health_controller.rb", f'class HealthController < ApplicationController\n  def show = render json: {{ status: "ok" }}\n  def index = render json: {{ name: "{request.project_name}", status: "ready" }}\nend'),
        file("config/database.yml", database_config),
        file("storage/.gitkeep", ""),
        file("test/health_test.rb", 'require "test_helper"\nclass HealthTest < ActiveSupport::TestCase\n  test("starter") { assert true }\nend'),
        file("test/test_helper.rb", 'ENV["RAILS_ENV"] ||= "test"\nrequire_relative "../config/environment"\nrequire "rails/test_help"'),
        *shared_files(request, "Ruby on Rails"),
    ]


def aspnet(request: GenerateRequest) -> list[GeneratedFile]:
    package = {
        "sqlite": '<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />',
        "postgresql": '<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />',
        "sqlserver": '<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />',
    }[request.database]
    return [
        file(
            f"{request.project_name}.csproj",
            f"""
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
              <ItemGroup>{package}</ItemGroup>
              <ItemGroup><Compile Remove="tests/**/*.cs" /></ItemGroup>
            </Project>
            """,
        ),
        file(
            "Program.cs",
            f'''
            var builder = WebApplication.CreateBuilder(args);
            var app = builder.Build();
            app.MapGet("/", () => Results.Ok(new {{ name = "{request.project_name}", status = "ready" }}));
            app.MapGet("/health", () => Results.Ok(new {{ status = "ok" }}));
            app.Run();
            public partial class Program {{ }}
            ''',
        ),
        file("appsettings.json", '{"Logging":{"LogLevel":{"Default":"Information"}},"AllowedHosts":"*"}'),
        file(
            "tests/GeneratedSmoke.Tests.csproj",
            f"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup><TargetFramework>net8.0</TargetFramework><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
              <ItemGroup>
                <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
                <PackageReference Include="xunit" Version="2.9.2" />
                <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
                <ProjectReference Include="../{request.project_name}.csproj" />
              </ItemGroup>
            </Project>
            """,
        ),
        file("tests/SmokeTests.cs", "using Xunit; public class SmokeTests { [Fact] public void StarterWorks() => Assert.True(true); }"),
        *shared_files(request, "ASP.NET Core"),
    ]


GENERATORS: dict[str, Callable[[GenerateRequest], list[GeneratedFile]]] = {
    "flask": flask,
    "react": react,
    "django": django,
    "node": lambda request: node_api(request, False),
    "vue": vue,
    "angular": angular,
    "fastapi": fastapi,
    "nextjs": nextjs,
    "svelte": svelte,
    "express": lambda request: node_api(request, True),
    "laravel": laravel,
    "spring": spring,
    "rails": rails,
    "aspnet": aspnet,
}


def generate_files(request: GenerateRequest) -> list[GeneratedFile]:
    return GENERATORS[request.framework_id](request)
